from typing import Any

class RWGltf_CafWriter:
    def __init__(self, file: Any, is_binary: bool) -> None: ...
    def SetMergeFaces(self, to_merge: bool) -> None: ...
    def SetSplitIndices16(self, to_split: bool) -> None: ...
    def Perform(self, document: Any, file_info: Any, progress: Any) -> bool: ...
